# vim: filetype=tmux :
############################################
##  PREFIX ALT + SPACE
############################################
unbind-key C-b
set -g prefix M-Space
bind-key M-Space send-prefix

############################################
##  GlOBAL SETTINGS
############################################
set -g base-index 1
set -g pane-base-index 1

bind-key -      split-window -v
bind-key |      split-window -h

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

#
