# vim: filetype=tmux :
############################################
##  PREFIX
############################################
#unbind-key C-b
#set -g prefix C-b
set -g prefix M-b
bind-key M-b send-prefix
bind-key C-b send-prefix

############################################
##  GlOBAL SETTINGS
############################################
set -g base-index 1
set -g pane-base-index 1

############################################
##  NAVIGATION
############################################
bind-key -      split-window -v
bind-key |      split-window -h

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

############################################
##  COPY MODE
############################################
unbind-key C-v
unbind-key C-V
set -g mode-keys vi
bind-key -n M-c copy-mode
bind-key -n M-p paste-buffer
